### PR TITLE
fix imagestream template

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by twaugh** [comment]
Is this because the ansible variable is a boolean but we need to set it as a YAML string?

**Comment by lcarva** [comment]
> Is this because the ansible variable is a boolean but we need to set it as a YAML string?

It's needed for ansible to treat it as an expression and actually evaluate it. I think :question:

**Comment by rcerven** [comment]
I was getting : Error from server (BadRequest): ImageStream in version "v1" cannot be handled as a ImageStream: [pos 108]: json: expect char '"' but got char 't'

without ""

**Comment by twaugh** [comment]
Can we explain that in the commit message? That we're converting the YAML value into a string?

**Pull request merged**
